### ISSUE TITLE
Feature request: Wait until the nozzle and bed cool down under defined temperature before power off

### ISSUE THREAD

**Issue by lpojzl** [ralmn/OctoPrint-Ikea-tradfri#22]
The plugin shall wait for the cool down below defined threshold prior switching the printer off.
Ideally, if the temperature is set to non-zero value, it shall override the timer setting and wait for cool down for safety reasons.

**Comment by Justheretoreportanissue** [comment]
May I please add my vote for this feature?

/Jonas...

**Comment by ralmn** [comment]
Release in [V1.6.0](https://github.com/ralmn/OctoPrint-Ikea-tradfri/releases/tag/1.6.0)

**Comment by ralmn** [comment]
You need to edit your device settings and set the "turn off mode" to "cooldown"
