### ISSUE TITLE
Can not delete printer

### ISSUE THREAD

**Issue by Pajje99** [ralmn/OctoPrint-Ikea-tradfri#26]
Hi,

When i try to setup this plugin i go in and change name of the printer and suddenly i have 2 printers. I can not delete any printers either.

![image](https://user-images.githubusercontent.com/16124303/99287062-0f02fb80-283a-11eb-94b6-8fbd2eaa28aa.png)

**Comment by ralmn** [comment]
Fix with 3329c4e260ea97d89f529d914b5a95469e697bf9 in v1.4.2

**Comment by Pajje99** [comment]
Sorry to open thi issue again but now the delete works but it deletes the wrong item.

I add a printer and then tries to delete the first, the one i made get deleted and the old one is left,

**Comment by ralmn** [comment]
I fix it in v1.4.3
