### ISSUE TITLE
Issue with only one Printer

### ISSUE THREAD

**Issue by Pajje99** [ralmn/OctoPrint-Ikea-tradfri#28]
I found a bug that does not show the Icon in the Navbar if there is only one printer defined.
If i add another printer the Icon shows and i can power on/off the printer.

**Comment by ralmn** [comment]
Do you have at least one of the options "nav icon" or "nav name" checked?
If yes, can you extract me from `config.yaml` the `selected_devices` section to understand the problem?

**Comment by ralmn** [comment]
Hello @Pajje99, do you still have this problem?

**Comment by ralmn** [comment]
any news ? I close this issues
