### ISSUE TITLE
Wrong API key freezes OctoPrint

### ISSUE THREAD

**Issue by crysxd** [ralmn/OctoPrint-Ikea-tradfri#30]
I just set up your plugin. Besides being extremely complicated to setup due to the manual install (had to create a custom Docker container), I struggled for like 45 minutes to connect it to my Tradfri bridge. I misread a single character (a instead of q) and every time I tried to click "Finish" in the wizard or "Save" in preferences the entire OctoPrint froze and I had to restart the entire machine. After finally realizing the typo, this issue was gone. Logs attached.
[octoprint (4).log](https://github.com/ralmn/OctoPrint-Ikea-tradfri/files/5760590/octoprint.4.log)

**Comment by ralmn** [comment]
I just released a new version (v1.5.0). I think it should fix the problem.

**Comment by crysxd** [comment]
Thanks!
