### ISSUE TITLE
Update to 1.5.2 not recognized

### ISSUE THREAD

**Issue by Thidsa** [ralmn/OctoPrint-Ikea-tradfri#33]
It installs without error, but after octoprint restart it has not updated.
Tell me what more you need
Bjørn

**Comment by ralmn** [comment]
What is the version of python used by octoprint? 
For information: version 1.5.x of the plugin is no longer compactible with python2.7.

**Comment by Thidsa** [comment]
Python 3.7.3
Current version of your plugin is 1.5.1 here

**Comment by ralmn** [comment]
Can you join the `octoprint.log`, `plugin_pluginmanager_console.log` and `plugin_softwareupdate_console.log` ?

**Comment by Thidsa** [comment]
plugin_pluginmanager_console.log was empty here......

[plugin_softwareupdate_console.log](https://github.com/ralmn/OctoPrint-Ikea-tradfri/files/5817323/plugin_softwareupdate_console.log)
[octoprint.log](https://github.com/ralmn/OctoPrint-Ikea-tradfri/files/5817324/octoprint.log)

**Comment by ralmn** [comment]
Ok... I found what happened... I have forgot to change a version in setup.py... The 1.5.3 fix that

**Comment by Thidsa** [comment]
yes works now, thanks
