### ISSUE TITLE
Cannot update via plugin manager - error with Python

### ISSUE THREAD

**Issue by langph** [ralmn/OctoPrint-Ikea-tradfri#36]
When I try to update to the latest version (from 1.4.4) I get the following error message:

/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/ralmn/OctoPrint-Ikea-tradfri/archive/1.5.4.zip --no-cache-dir
Collecting https://github.com/ralmn/OctoPrint-Ikea-tradfri/archive/1.5.4.zip
Downloading https://github.com/ralmn/OctoPrint-Ikea-tradfri/archive/1.5.4.zip
OctoPrint-Ikea-Tradfri requires Python '>3,<4' but the running Python is 2.7.13
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by ralmn** [comment]
Starting 1.5, the plugin is not compatible with python 2.7. I recommend to upgrade you octoprint to Python 3 https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
