### ISSUE TITLE
Issue with Python version - Probleme avec la version du python

### ISSUE THREAD

**Issue by Dedcap** [ralmn/OctoPrint-Ikea-tradfri#37]
Hello,

When I try to install it from the zip, it throw me due to a bad version of python
If I try to download the file my self, it don't throws me anymore for the python but after the restar of Octo, it crashes and oblige me to restart in safe mode and uninstall the plugin

Can you advise me how to proceed?

Thanks

**Comment by Dedcap** [comment]
Hi,

I have updated octo to have it with python 3
Now the plugin is installed and I can click on the icon to switch off and on the Ikea plug

Is it possible to have octo switching off the plug at the end of a print?
I try to configure this with your plugin but unfortunately it look like to do know works

**Comment by ralmn** [comment]
I close this issue, your problem is solved
