### ISSUE TITLE
Outlet icon is always red 1.7.0

### ISSUE THREAD

**Issue by Thidsa** [ralmn/OctoPrint-Ikea-tradfri#41]
Icon doesnt turn green anymore when outlet is on. Not sure since when

**Comment by nestorix1343** [comment]
> Icon doesnt turn green anymore when outlet is on. Not sure since when

My feeling is since 1.7.0. 

This has happened before I think and it got fixed quite fast.

**Comment by ralmn** [comment]
On one of my printer, it's work... But I will see in more detail why it's happend... Can I have your `octoprint.log` ?

**Comment by ralmn** [comment]
I just had the problem... It seems that it is the ikea gateway that did not respond in my case... A periodic check should help... even if it's not the best...

**Comment by Thidsa** [comment]
Respond how?
Here it works like it should, atleast the controlling of the plug. Can try to restart the gateway
Still need a log?

**Comment by ralmn** [comment]
My gateway timeout. 
Yes if you can send me logs, for see if it's the same error

**Comment by Thidsa** [comment]
[octoprint.log](https://github.com/ralmn/OctoPrint-Ikea-tradfri/files/6216554/octoprint.log)

**Comment by ralmn** [comment]
Ok there is a real problem when the MQTT plugin is not enabled. v1.7.1 will fix this :)

**Comment by ralmn** [comment]
https://github.com/ralmn/OctoPrint-Ikea-tradfri/releases/tag/1.7.1
