### ISSUE TITLE
SerialException on shutdown

### ISSUE THREAD

**Issue by luketot** [ralmn/OctoPrint-Ikea-tradfri#43]
Whenever the printer is shut off by killing the power, it results in a serial exception in the Octoprint terminal.

This made it difficult to troubleshoot when i actually had serial communication issues, and my serial log was filled with exceptions from everytime the plugin turned off the printer.

Would it be possible for the plugin to disconnect the printer from Octoprint nicely before killing the power?

Alternatively, if it could send gcodes before issuing the shutdown, I could have it send "M118 A1 action:disconnect".

**Comment by poulanker** [comment]
@ralmn I really love not having to go to the printer to turn it on or off, but It is quite annoying that the connection is not closed, before the printer is powered off by this plugin.
Besides cluttering the serial log with exception errors, it also forces OctoPrint to show a communication error dialog box.

Please implement a change,  that sends the "Disconnect Printer" command to OctoPrint before sending the "PowerOff" command to the Ikea outlet.

**Comment by ralmn** [comment]
Fix in 1.7.3
