### ISSUE TITLE
Request: try to connect printer a short while after turning on the power to the printer

### ISSUE THREAD

**Issue by sigboe** [ralmn/OctoPrint-Ikea-tradfri#52]
Hello, 
I would like the printer to auto connect the remembered connection setting after the IKEA plug is turned on.
Either a set amount of time after, or just retry, or if it is possible to detect when the printer is ready.

**Comment by ralmn** [comment]
You can already define the delay in the settings of your plug in Octoprint in the "Auto connect" section

**Comment by sigboe** [comment]
Sorry, I didn't notice, my bad

**Comment by ralmn** [comment]
No problem :)
