### ISSUE TITLE
Feature request: Offer choice of icons on settings page.

### ISSUE THREAD

**Issue by pedrocadiz13** [ralmn/OctoPrint-Ikea-tradfri#9]
I use the PSU Control plugin to control the  power to my 3d printer via a relay attached to the raspberry pi on which Octoprint is running. I'd like to use this plugin to control LEDS attached to the printer.

Would be nice if you could offer a choice of icons including a bulb icon to show that it's lighting that's being controlled.

**Comment by ralmn** [comment]
It will be available in next update. If you want now you can install via manual install  `https://github.com/ralmn/OctoPrint-Ikea-tradfri/archive/master.zip `
